# Generated by Django 5.1.6 on 2025-03-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
