# Generated by Django 5.1.6 on 2025-03-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crowdFunding.project'),
        ),
    ]
