# Generated by Django 5.1.6 on 2025-03-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReprotComment',
            new_name='ReportComment',
        ),
        migrations.RenameField(
            model_name='reportcomment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reportcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
