# Generated by Django 5.1.6 on 2025-03-03 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0002_rename_reprotcomment_reportcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='total_user_rated',
            field=models.IntegerField(default=0),
        ),
    ]
