# Generated by Django 5.1.6 on 2025-03-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0005_rename_tag_project_tags_rename_user_id_project_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
    ]
