# Generated by Django 5.1.6 on 2025-03-03 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSelected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crowdFunding.project')),
            ],
        ),
    ]
