# Generated by Django 5.1.6 on 2025-03-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0006_projectselected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectSelected',
            new_name='SelectedProject',
        ),
    ]
