# Generated by Django 5.1.6 on 2025-03-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0006_remove_project_start_time'),
        ('crowdFunding', '0007_rename_projectselected_selectedproject'),
    ]

    operations = [
    ]
